// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: "2024-04-03",

  devtools: { enabled: true },

  app: {
    head: {
      title: "LoveSpot | Surpreenda quem você ama!",
    },
  },

  css: ["primeicons/primeicons.css"],

  modules: [
    "@nuxtjs/tailwindcss",
    "@primevue/nuxt-module",
    "@nuxt/icon",
    "@nuxt/eslint",
    "@nuxt/fonts",
    "vue-clerk/nuxt",
    "@vueuse/nuxt",
  ],

  typescript: {
    typeCheck: true,
  },

  runtimeConfig: {
    tursoDBURL: process.env.TURSO_DATABASE_URL,
    tursoAuthToken: process.env.TURSO_AUTH_TOKEN,
  },

  primevue: {
    importTheme: { from: "./assets/css/preset.ts" },
    options: {
      locale: {
        accept: "Sim",
        addRule: "Adicionar Regra",
        am: "AM",
        apply: "Aplicar",
        cancel: "Cancelar",
        choose: "Escolher",
        chooseDate: "Escolher Data",
        chooseMonth: "Escolher Mês",
        chooseYear: "Escolher Ano",
        clear: "Limpar",
        completed: "Concluído",
        contains: "Contém",
        dateAfter: "Data depois de",
        dateBefore: "Data antes de",
        dateFormat: "dd/MM/yy",
        dateIs: "Data é",
        dateIsNot: "Data não é",
        dayNames: [
          "Domingo",
          "Segunda-feira",
          "Terça-feira",
          "Quarta-feira",
          "Quinta-feira",
          "Sexta-feira",
          "Sábado",
        ],
        dayNamesMin: ["D", "S", "T", "Q", "Q", "S", "S"],
        dayNamesShort: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"],
        emptyFilterMessage: "Nenhum resultado encontrado",
        emptyMessage: "Nenhuma opção disponível",
        emptySearchMessage: "Nenhum resultado encontrado",
        emptySelectionMessage: "Nenhum item selecionado",
        endsWith: "Termina com",
        equals: "Igual",
        fileSizeTypes: ["B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB"],
        firstDayOfWeek: 0,
        gt: "Maior que",
        gte: "Maior ou igual a",
        lt: "Menor que",
        lte: "Menor ou igual a",
        matchAll: "Corresponder Todos",
        matchAny: "Corresponder Qualquer",
        medium: "Médio",
        monthNames: [
          "Janeiro",
          "Fevereiro",
          "Março",
          "Abril",
          "Maio",
          "Junho",
          "Julho",
          "Agosto",
          "Setembro",
          "Outubro",
          "Novembro",
          "Dezembro",
        ],
        monthNamesShort: [
          "Jan",
          "Fev",
          "Mar",
          "Abr",
          "Mai",
          "Jun",
          "Jul",
          "Ago",
          "Set",
          "Out",
          "Nov",
          "Dez",
        ],
        nextDecade: "Próxima Década",
        nextHour: "Próxima Hora",
        nextMinute: "Próximo Minuto",
        nextMonth: "Próximo Mês",
        nextSecond: "Próximo Segundo",
        nextYear: "Próximo Ano",
        noFilter: "Sem Filtro",
        notContains: "Não contém",
        notEquals: "Diferente",
        passwordPrompt: "Digite uma senha",
        pending: "Pendente",
        pm: "PM",
        prevDecade: "Década Anterior",
        prevHour: "Hora Anterior",
        prevMinute: "Minuto Anterior",
        prevMonth: "Mês Anterior",
        prevSecond: "Segundo Anterior",
        prevYear: "Ano Anterior",
        reject: "Não",
        removeRule: "Remover Regra",
        searchMessage: "Existem {0} resultados disponíveis",
        selectionMessage: "{0} itens selecionados",
        showMonthAfterYear: false,
        startsWith: "Começa com",
        strong: "Forte",
        today: "Hoje",
        upload: "Enviar",
        weak: "Fraco",
        weekHeader: "Sem",
      },
    },
  },
});
